name: Node.js CI

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install
      - name: Test
        run: echo $STRING_SECRET
        env:
          STRING_SECRET: ${{ secrets.TEST_SECRET }}
